config/routes.rb
Rails.application.routes.draw do
  get 'options/create'
  get 'messages/new'
  get 'messages/create'
  get 'polls/new'
  get 'polls/create'
  get 'activities/new'
  get 'activities/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :plans do
    resources :activities, only: [:new, :create]
    resources :polls, only: [:new, :create]
    resources :messages, only: [:new, :create]
    resources :participants, only: [:new, :create, :update]
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :plan
  validates :title, presence: true
  validates :location, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :participant
  belongs_to :plan
  has_many :participants
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll
  has_many :votes
end

app/models/participant.rb
class Participant < ApplicationRecord
  STATUSES = %w[Pending Going Not\ Going Maybe]
  belongs_to :user
  belongs_to :plan
  has_many :plans, -> { order(start_datetime: :asc) }
  has_many :users
  # validates :status, presence: true
  validates :user_id, uniqueness: { scope: :plan_id,
                                    message: "not the same friend" }
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :polls
  has_many :participants, dependent: :destroy
  has_many :activities
  validates :title, presence: true
  validates :location, presence: true
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :plan
  has_many :options
  validates :question, presence: true
  validates :option, length: { minimum: 2 }
  STATUS = %w[Going NotGoing Maybe Pending]
  validates :status, inclusion: { in: STATUS }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ...Avatar Attachment...
  has_one_attached :avatar_picture

  # Validations
  validates :avatar_picture, file_size: { less_than_or_equal_to: 5.megabytes },
                             file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :option
  belongs_to :participant
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_plan, only: %i[new create]
  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activities_params)
    @activity.plan = @plan
    @activity.save
    # redirect_to plan_path(@plan)
  end

  private

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def activities_params
    params.require(:activity).permit(:start_datetime, :end_datetime, :location, :cost, :title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])

    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar_picture])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_plan, only: %i[new create]
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(messages_params)
    @message.plan = @plan
    @message.save
    # redirect_to plan_path(@plan)
  end

  private

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def messages_params
    params.require(:message).permit(:content)
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def create

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def create

    @plan = Plan.find(params[:plan_id])
    @participant = Participant.new
    @participant.plan = @plan
    @user = User.find_by(nickname: params["participant"]["user"])
    if @user == current_user
      redirect_to plan_path(@plan), notice: "You are already going"
    else
      @participant.user = @user
      respond_to do |format|
        if @participant.save
          format.html { redirect_to plan_path(@plan) }
          format.json # Follow the classic Rails flow and look for a create.json view
        else
          format.html { redirect_to plan_path(@plan), status: :unprocessable_entity }
          format.json # Follow the classic Rails flow and look for a create.json view
        end
      end
    end
  end

  def update
    @participant = Participant.find(params[:id])
    @participant.update(participant_params)
    redirect_to plan_path(@participant.plan)
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end

  def participant_params
    params.require(:participant).permit(:status)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[show edit update destroy]
  def index
    # @plans = Plan.all
    @user = current_user
    @plans = Plan.order(start_datetime: :asc)
    @plans_active = @plans.where(start_datetime: (Time.now)..)
    @plans_planner = @plans_active.where(planner_id: current_user.id)
    @plans_participant = @plans_active.joins(:participants).where(participants: { user_id: current_user.id })
    @plans_going_participant = @plans_participant.joins(:participants).where(participants: { status: "Going" })
    @plans_going_all = @plans_going_participant | @plans_planner
    @plans_going_order = @plans_going_all.sort_by { |plan| plan[:start_datetime] }
    @plans_participant_status = @plans_participant.joins(:participants).where.not(participants: { status: ["Going", "Not Going"] })
    @plans_participant_status_decline = @plans_participant.joins(:participants).where(participants: { status: "Not Going" })
    @participant = Participant.all
    # @participant = Participant.find_by(user_id: current_user.id)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.planner_id = current_user.id
    @plan.image = api_image
    @plan.save!
    redirect_to plan_path(@plan)
  end

  def edit
    # @participant = Participant.new
  end

  def show
    @users = User.all
    @participant = Participant.new
    @current_participant = @plan.participants.find_by(user: current_user)
    @participants = @plan.participants
    @plans = @plan
    numero = @plan.planner_id
    @organiser = User.find_by_id(numero)
    @markers =
      [{
        lat: @plan.latitude,
        lng: @plan.longitude
      },
       {
         lat: @plan.latitude,
         lng: @plan.longitude
       }]
    # @poll = Poll.new
    # @message = Message.new
    # @option = Option.new
  end

  def update
    @plan.update(plan_params)
    redirect_to plan_path(@plan)
  end

  def destroy
    @plan.destroy
    redirect_to plans_path, status: :see_other
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:title, :location, :cost, :description, :start_datetime, :end_datetime)
  end

  def user_params
    params.require(:user).permit(:nickname)
  end

  def api_image
    @client = Pexels::Client.new(ENV.fetch('PEXELS_API_KEY'))
    @photo = @client.photos.search("#{@plan.title}", per_page: 1).first
    # photo = @client.photos[@photo.id]
    @plan.image = @photo.src["landscape"]
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_plan, only: %i[new create]
  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(polls_params)
    @poll.plan = @plan
    @poll.save
    # redirect_to plan_path(@plan)
  end

  private

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def polls_params
    params.require(:poll).permit(:question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/new.html.erb
<h1>Activities#new</h1>
<p>Find me in app/views/activities/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planit - Planning assistant hub for social gatherings and events</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- specify the icon for iOS devices -->
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>
    <%= yield %>
  </body>
  <%= render "shared/footer" %>
</html>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/options/create.html.erb
<h1>Options#create</h1>
<p>Find me in app/views/options/create.html.erb</p>

app/views/plans/_participant_status.html.erb
<small class="d-inline-flex mb-1 px-2 py-1">
           <% if participant.user.avatar_picture.present? %>
             <%= cl_image_tag(participant.user.avatar_picture.key, alt: 'Yes', width: 42, height: 42, class: participant.status) %>
           <% else %>
             <%= image_tag "avatarhome1.png", alt: "Avatar", width: 42, height: 42, class: participant.status %>
           <% end %>
       </small>

app/views/plans/edit.html.erb
<h1>Plans#edit</h1>
<p>Find me in app/views/plans/edit.html.erb</p>
<div class="container-fluid">
<div class="row gx-0 mt-3">
<%= render "shared/add_plan_form" %>
<%= link_to 'Back', plan_path(@plan) %>
</div>

app/views/plans/index.html.erb
<div class="container-fluid">

<p class="mt-3 mb-0">Hello <font color="#ff66b3ff"><%= current_user.nickname %></font></p>


  <h1 class="cocol mt-0 mb-3">Your upcoming plans</h1>
<!-- Going New Large Card style -->
<div class="row px-1 mb-3">
<div class="row flex-nowrap overflow-auto">
   <% @plans_going_order.each do |plan| %>
    <a href="<%= plan_path(plan) %>">
  <div class="col">
    <div class="card ms-1 me-2 card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: linear-gradient(-10deg, rgba(0, 0, 0, 1), rgba(0, 0, 0, 0.1)), url('<%= plan.image %>');">
      <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold"><%= plan.title %></h3>
        <ul class="d-flex list-unstyled mt-auto">

          <li class="nav-item dropdown">
          <% numero = plan.planner_id %>
          <%@organiser = User.find_by_id(numero) %>
                <% if @organiser.avatar_picture.present? %>
              <%= cl_image_tag(@organiser.avatar_picture.key, alt: 'Yes', width: 32, height: 32, class: "avatar-image rounded-circle border border-white") %>
          <li class="me-auto">
            <% else %>
              <%= image_tag "avatarhome1.png", alt: "Avatar", class: "ms-0 me-3" %>
            <% end %>
          </li>
          <li class="d-flex align-items-center me-3">
            <i class="bi bi-geo-fill me-2"></i>
            <small class="cocoxs"><%= plan.location %></small>
          </li>
          <li class="d-flex align-items-center">
            <i class="bi bi-calendar3 me-2"></i>
            <small class="cocoxs">
            <%= ((plan.start_datetime - DateTime.now)/86400).to_i %>d</small>
          </li>
        </ul>
      </div>
    </div>
    </div>
    <% end %>
  </div>
</a>
</div>

    <!-- All status but decline Start of Old Card Style -->
                <div class="row gx-0">
                <div class="row flex-nowrap overflow-auto">
<% @plans_participant_status.each do |plan| %>
 <a href="<%= plan_path(plan) %>">
    <div class="card me-2 mb-3" style="max-width: 560px;">
            <!-- create a row with no gutters between columns -->
    <div class="row flex-nowrap overflow-auto">
                <!-- on small screens, take up the entire width of the row and order it first -->
                <!-- on medium screens and up, take up half the width of the row -->
                <div class="col order-2 col-md-6  d-flex flex-column">
                    <!-- add the card content in a card-body div -->
                    <div class="card-body d-flex flex-column justify-content-between ps-0 pe-3 pt-3 pb-3">
                        <div>
                            <h5 class="card-title"><%= plan.title %></h5>
                             <h6 class="cocol card-subtitle text-muted mb-2"><% if plan.start_datetime.strftime('%-d') < plan.end_datetime.strftime('%-d') %> <%= plan.start_datetime.strftime('%a %e %b · %-l:%M') %>		                             <h6 class="cocol card-subtitle text-muted mb-2"><% if plan.start_datetime.strftime('%-d') < plan.end_datetime.strftime('%-d') %> <%= plan.start_datetime.strftime('%a %e %b · %-l:%M') %>
 -<%= plan.end_datetime.strftime('%a %-d %b · %-l:%M%P') %> <% else %> <%= plans.first.start_datetime.strftime('%a %e %b · %-l:%M') %>-<%= plans.first.end_datetime.strftime('%-l:%M%P') %> <% end %></h6>		 -<%= plan.end_datetime.strftime('%a %-d %b · %-l:%M%P') %> <% else %> <%= plan.start_datetime.strftime('%a %e %b · %-l:%M') %>-<%= plan.end_datetime.strftime('%-l:%M%P') %> <% end %></h6>
                              <p class="cocoxs card-text mb-2"> <%= plan.description %> </p>
                        </div> <!-- add two buttons, one for "Going" and one for "Chat" -->
                        <div>
                          <% plan.participants.each do |participant| %>
                            <% if participant.user_id == current_user.id %>
                              <div class="d-flex justify-content-between"> <button type="button" class="btn btn-outline-success <%= participant.status %>"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-question-fill" viewBox="0 0 16 16">
                                <path d="M5.933.87a2.89 2.89 0 0 1 4.134 0l.622.638.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636zM7.002 11a1 1 0 1 0 2 0 1 1 0 0 0-2 0zm1.602-2.027c.04-.534.198-.815.846-1.26.674-.475 1.05-1.09 1.05-1.986 0-1.325-.92-2.227-2.262-2.227-1.02 0-1.792.492-2.1 1.29A1.71 1.71 0 0 0 6 5.48c0 .393.203.64.545.64.272 0 .455-.147.564-.51.158-.592.525-.915 1.074-.915.61 0 1.03.446 1.03 1.084 0 .563-.208.885-.822 1.325-.619.433-.926.914-.926 1.64v.111c0 .428.208.745.585.745.336 0 .504-.24.554-.627z"></path>
                                  </svg>
                                    <%= participant.status%>
                                  </button>
                                </div>
                              <% end %>
                            <% end %>
                        </div>
                    </div>
                </div> <!-- on small screens, take up the entire width of the row and order it first -->

                <div class="col order-1" style="max-height: 220px;">
                    <img src= <%= plan.image %> class="img-fluid rounded-start h-100 object-fit-cover object-position-center" alt="">
                </div>
            </div>
        </div>
         <% end %>
    </div>
</a>
</div>

<!-- Decline Small Card Section -->
    <div class="row gx-0">
    <div class="row flex-nowrap overflow-auto">
     <% @plans_participant_status_decline.each do |plan| %>
<a href="<%= plan_path(plan) %>">
     <div class="card light-border-subtle mb-3 me-2">
            <div class="card-body row">
                <div class="col-9">
                    <h5 class="card-title text-muted"><%= plan.title %></h5>
                    <h6 class="cocol card-subtitle text-muted mb-2"><% if plan.start_datetime.strftime('%-d') < plan.end_datetime.strftime('%-d') %> <p><%= plan.start_datetime.strftime('%a %e %b · %-l:%M') %>
-<%= plan.end_datetime.strftime('%a %-d %b · %-l:%M%P') %></p> <% else %> <p class="time-mb"><%= plan.start_datetime.strftime('%a %e %b · %-l:%M') %>-<%= plan.end_datetime.strftime('%-l:%M%P') %></p> <% end %></h6>
                </div>
            </div>
        </div> <% end %> </div>
        </div>
</a>

<!-- Suggestion Card Section -->
    <div class="row gx-0">
        <h2 class="cocol">Ideas for new plans</h2>
        <div class="row flex-nowrap overflow-auto">
<!-- Suggestion Card single -->
          <div class="card mb-3 me-2">
  <div class="card-body row">
    <div class="col-4">
      <button type="button" class="btn btn-warning">
        <i class="fa-solid fa-pizza-slice"></i>
      </button>
    </div>
    <div class="col-8 text-end">
      <h5 class="card-title">Pizza Night</h5>
    </div>
  </div>
</div>
<div class="card mb-3 me-2">
  <div class="card-body row">
    <div class="col-4">
      <button type="button" class="btn btn-danger">
        <i class="fa-solid fa-guitar"></i>
      </button>
    </div>
    <div class="col-8 text-end">
      <h5 class="card-title">Gig</h5>
    </div>
  </div>
</div>
<!-- Suggestion Card Single End -->
        </div>
  </div>

<!-- Suggestion Card Section -->
    <div>
        <button class="menu-btn">+
          <%= link_to new_plan_path do %>
            <span class="bi bi-plus-circle"></span>
          <% end %>
          <span class="bi bi-pass"></span>
          <span class="bi bi-patch-question"></span>
        </button>
        </div>


            <script>
                const menuBtn = document.querySelector('.menu-btn');
                menuBtn.addEventListener('click', function() {
                  this.classList.toggle('active');
                });
            </script>
        </div>
    </div>

app/views/plans/new.html.erb
<div class="container-fluid">
<div class="row gx-0 mt-3">
<%= render "shared/add_plan_form" %>
</div>

app/views/plans/show.html.erb
<img src="<%= @plan.image %>" alt="" class="plan-image">
<div class="container-fluid bg-white" data-controller="jumping" data-jumping-position-value="beforeend">
  <div class="card">
    <div class="card-body">
      <div class="row align-items-center">
        <div class="col">
          <div class="back-btn mb-2">
            <%= link_to plans_path do %>
              <i class="bi bi-chevron-left"></i> all plans
            <% end %>
          </div>
        </div>
        <div class="col">
          <div class="d-flex flex-row-reverse">
            <div class="p-2">
              <%= link_to '<i class="bi bi-pencil-fill"></i>'.html_safe, edit_plan_path(@plan) %>
            </div>
            <div class="p-2">
              <%= link_to '<i class="bi bi-trash-fill"></i>'.html_safe, plan_path(@plan), data: {
                turbo_method: :delete
              } %>
            </div>
          </div>
        </div>
      </div>
      <div class="row align-items-center">
        <div class="col">
          <h1 class="display-6" data-jumping-target="name"><%= @plan.title %></h1>
        </div>
        <div class="col d-flex justify-content-end">
  <% if @organiser != current_user %>
  <div class="d-flex align-items-center" data-controller="dropdown">
    <%= render "shared/add_status_form" %>
  </div>
<% end %>
</div>
      </div>
      <p><%= @plan.description %></p>


<div class="d-flex align-items-center pb-1">
  <i class="bi bi-piggy-bank-fill"></i>
  <span class="ms-2">£<%= @plan.cost.to_i %></span></span>
</div>
<div class="d-flex align-items-center pb-1">
  <i class="bi bi-stars" ></i>
  <span class="ms-2"><%= @organiser == current_user ? "You are" : "#{@organiser.nickname} is"%> organising</span>

</div>
<div class="d-flex align-items-center pb-1">
  <i class="bi bi-clock-fill"></i>
  <span class="ms-2"><%= @plan.start_datetime.strftime('%a %e %b %l:%M %p') %></span>
</div>
<div class="d-flex align-items-center pb-1">
  <i class="bi bi-geo-alt-fill"></i>
  <span class="ms-2"><%= @plan.location %></span>
</div>
<div class="d-flex align-items-center pb-1">
  <i class="bi bi-people-fill"></i>
  <div class="ms-2 participants" data-jumping-target="participant">
    <% @plan.participants.each do |participant| %>

            <%= render "plans/participant_status", participant: participant %>

    <% end %>
  </div>
</div>

<%= render "shared/add_friends_form" %>



<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>
</div>

app/views/polls/create.html.erb
<h1>Polls#create</h1>
<p>Find me in app/views/polls/create.html.erb</p>

app/views/polls/new.html.erb
<h1>Polls#new</h1>
<p>Find me in app/views/polls/new.html.erb</p>

app/views/shared/_add_friends_form.html.erb
<%= simple_form_for([@plan, @participant], data: {jumping_target: "form", action: "submit->jumping#send"}) do |f| %>
  <div class="form-group d-flex align-items-center mb-3 mt-3">
    <div class="submit-wrapper">
      <%= f.submit "+", class: "btn btn-primary rounded-circle me-2" %>
    </div>
    <%= f.text_field :user, list: 'user-list', autocomplete: 'off', class: "form-control", placeholder: "Add your friend", data: {jumping_target: "name"} %>
    <datalist id="user-list">
      <% for user in User.all.select(:nickname) %>
        <option><%= user.nickname %></option>
      <% end %>
    </datalist>
  </div>
<% end %>

app/views/shared/_add_plan_form.html.erb
<%= simple_form_for @plan, data: { controller: 'flatpickr' } do |f| %>
  <%= f.input :title, label: "What's the plan?" %>
  <%= f.input :description %>
  <%= f.input :start_datetime, label: "Set start ", as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
  <%= f.input :end_datetime, label: "Set end ", as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
  <%= f.input :cost, label: 'Budget per friend' %>
  <%= f.input :location %>
  <%= submit_tag "Planit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_add_status_form.html.erb
<%= simple_form_for([@plan, @current_participant]) do |f| %>
  <%=f.select :status, %w[Pending Going Not\ Going Maybe], {}, { onchange: 'this.form.submit()' } %>
<% end %>

app/views/shared/_evntcard.html.erb
<div class="card mb-3 me-2">
  <div class="card-body row">
    <div class="col-4">
      <button type="button" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-patch-plus-fill" viewBox="0 0 16 16">
  <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zM8.5 6v1.5H10a.5.5 0 0 1 0 1H8.5V10a.5.5 0 0 1-1 0V8.5H6a.5.5 0 0 1 0-1h1.5V6a.5.5 0 0 1 1 0z"/>
</svg>
      </button>
    </div>
    <div class="col-8 text-end">
      <h5 class="card-title">Event title</h5>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-3" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-3" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_flatpickr.html.erb
<%= simple_form_for([@plan], data: { controller: 'flatpickr' }) do |f| %>
     <%= f.input :start_datetime, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
    <%= f.input :end_datetime, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>
    <%= f.submit 'Book', class: 'btn btn-primary' %>
  <% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-3 my-1">
    <ul class="nav justify-content-start border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="/plans" class="nav-link px-2 text-muted">Plans</a></li>
      <li class="nav-item"><a href="/users/edit" class="nav-link px-2 text-muted">Profile</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="/about" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-left text-muted ms-1">© 2023 Planit</p>
  </footer>
</div>

app/views/shared/_txtcard.html.erb
<div class="card">
      <div class="card-body">
        <h5 class="card-title">Event title</h5>
        <h6 class="card-subtitle mb-2 text-muted">Thu 19 Sep · 7-9pm</h6>
        <p class="card-text">
          Some quick example text to for under the card title.
        </p>
      </div>
</div>